{
 "title": "Host metrics",
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "description": "16 core - max 1600%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  rate(system_cpu_time_seconds_total{state!=\"idle\"}[5m])\n)\n* 100\n",
     "legendFormat": "16 cores cpu %"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(system_cpu_time_seconds_total{state!=\"idle\"}[5m])\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(direction) (rate(system_network_io_bytes_total[5m])) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(direction) (rate(system_disk_io_bytes_total[5m])) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (state) (system_memory_usage_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File System memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{mountpoint=\"/\", state=\"used\"} / (1024^3)",
     "legendFormat": "used"
    },
    {
     "expr": "system_filesystem_usage_bytes{mountpoint=\"/\", state=\"free\"} / (1024^3)",
     "legendFormat": "free"
    },
    {
     "expr": "system_filesystem_usage_bytes{mountpoint=\"/\", state=\"reserved\"} / (1024^3)",
     "legendFormat": "reserved"
    }
   ]
  }
 ]
}