{
 "title": "RPC Request/Response Size",
 "panels": [
  {
   "title": "Average Request/Response Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (rpc_method)(\n  rate(\n    rpc_server_request_size_bytes_sum{\n      exported_job=\"arkd\",\n      rpc_system=\"grpc\"\n    }[5m]\n  )\n)\n/\nsum by (rpc_method)(\n  rate(\n    rpc_server_request_size_bytes_count{\n      exported_job=\"arkd\",\n      rpc_system=\"grpc\"\n    }[5m]\n  )\n)\n",
     "legendFormat": "{{rpc_method}} req"
    },
    {
     "expr": "sum by (rpc_method)(\n  rate(\n    rpc_server_response_size_bytes_sum{\n      exported_job=\"arkd\",\n      rpc_system=\"grpc\"\n    }[5m]\n  )\n)\n/\nsum by (rpc_method)(\n  rate(\n    rpc_server_response_size_bytes_count{\n      exported_job=\"arkd\",\n      rpc_system=\"grpc\"\n    }[5m]\n  )\n)\n",
     "legendFormat": "{{rpc_method}} resp"
    }
   ]
  },
  {
   "title": "Request/Response Size p50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_request_size_bytes_bucket{\n        exported_job=\"arkd\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} req"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_response_size_bytes_bucket{\n        exported_job=\"arkd\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} resp"
    }
   ]
  },
  {
   "title": "Request/Response size p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_request_size_bytes_bucket{\n        exported_job=\"arkd\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} req"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_response_size_bytes_bucket{\n        exported_job=\"arkd\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} resp"
    }
   ]
  }
 ]
}