{
 "title": "RPC Latency",
 "panels": [
  {
   "title": "Requests Count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_server_duration_milliseconds_count\n",
     "legendFormat": "{{rpc_method}} RPS"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(\n  sum by (rpc_method)(\n    rate(rpc_server_duration_milliseconds_sum{\n      exported_job=\"arkd\",\n      rpc_grpc_status_code=\"0\",\n      rpc_system=\"grpc\"\n    }[5m])\n  )\n)\n/\n(\n  sum by (rpc_method)(\n    rate(rpc_server_duration_milliseconds_count{\n      exported_job=\"arkd\",\n      rpc_grpc_status_code=\"0\",\n      rpc_system=\"grpc\"\n    }[5m])\n  )\n)\n",
     "legendFormat": "{{rpc_method}} mean"
    }
   ]
  },
  {
   "title": "Latency (p50 & p95)",
   "type": "timeseries",
   "description": "A percentile (e.g. the 95th percentile, or p95) is the value below which a given percentage of observations fall.\np95 means 95% of requests finished at or below that latency.\n\nExample:\nSuppose you have the following latency distribution for 100 requests:\n\n85 requests under 50ms\n10 requests around 200ms\n5 requests around 1,000ms (1 second)\nAverage:\n(85 * 50 + 10 * 200 + 5 * 1000) / 100 ≈ 92.5ms\np50 = ~50ms (since at least 50% of requests are at 50ms or lower)\np90 = ~200ms (90% of requests at 200ms or below)\np95 = ~1,000ms (95% of requests at 1,000ms or below)\nSo an average of ~92.5ms might look “fine,” but p95 being 1,000ms indicates 5% of requests take 1 second—a big difference for those users. \n\nProblem with average:\nIf your distribution is skewed—imagine most calls take ~50ms, but occasionally some calls take 1,000ms—the average can be pulled up by these outliers, giving you a number that doesn’t represent the typical user experience.\n\np95 helps you spot slow “tail latency” even when 95% of requests might look fine.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_duration_milliseconds_bucket{\n        exported_job=\"arkd\",\n        rpc_grpc_status_code=\"0\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} p50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, rpc_method) (\n    rate(\n      rpc_server_duration_milliseconds_bucket{\n        exported_job=\"arkd\",\n        rpc_grpc_status_code=\"0\",\n        rpc_system=\"grpc\"\n      }[5m]\n    )\n  )\n)\n",
     "legendFormat": "{{rpc_method}} p95"
    }
   ]
  }
 ]
}