version: "1.0"

description: "Simulation"

clients:
  - id: "client_0"
    name: "Client0"
  - id: "client_1"
    name: "Client1"
  - id: "client_2"
    name: "Client2"
  - id: "client_3"
    name: "Client3"
  - id: "client_4"
    name: "Client4"
  - id: "client_5"
    name: "Client5"
  - id: "client_6"
    name: "Client6"
  - id: "client_7"
    name: "Client7"
  - id: "client_8"
    name: "Client8"
  - id: "client_9"
    name: "Client9"
  - id: "client_10"
    name: "Client10"
  - id: "client_11"
    name: "Client11"
  - id: "client_12"
    name: "Client12"
  - id: "client_13"
    name: "Client13"
  - id: "client_14"
    name: "Client14"
  - id: "client_15"
    name: "Client15"
  - id: "client_16"
    name: "Client16"
  - id: "client_17"
    name: "Client17"
  - id: "client_18"
    name: "Client18"
  - id: "client_19"
    name: "Client19"
  - id: "client_20"
    name: "Client20"
  - id: "client_21"
    name: "Client21"
  - id: "client_22"
    name: "Client22"
  - id: "client_23"
    name: "Client23"
  - id: "client_24"
    name: "Client24"
  - id: "client_25"
    name: "Client25"
  - id: "client_26"
    name: "Client26"
  - id: "client_27"
    name: "Client27"
  - id: "client_28"
    name: "Client28"
  - id: "client_29"
    name: "Client29"
  - id: "client_30"
    name: "Client30"
  - id: "client_31"
    name: "Client31"
  - id: "client_32"
    name: "Client32"
  - id: "client_33"
    name: "Client33"
  - id: "client_34"
    name: "Client34"
  - id: "client_35"
    name: "Client35"
  - id: "client_36"
    name: "Client36"
  - id: "client_37"
    name: "Client37"
  - id: "client_38"
    name: "Client38"
  - id: "client_39"
    name: "Client39"
  - id: "client_40"
    name: "Client40"
  - id: "client_41"
    name: "Client41"
  - id: "client_42"
    name: "Client42"
  - id: "client_43"
    name: "Client43"
  - id: "client_44"
    name: "Client44"
  - id: "client_45"
    name: "Client45"
  - id: "client_46"
    name: "Client46"
  - id: "client_47"
    name: "Client47"
  - id: "client_48"
    name: "Client48"
  - id: "client_49"
    name: "Client49"
  - id: "client_50"
    name: "Client50"
  - id: "client_51"
    name: "Client51"
  - id: "client_52"
    name: "Client52"
  - id: "client_53"
    name: "Client53"
  - id: "client_54"
    name: "Client54"
  - id: "client_55"
    name: "Client55"
  - id: "client_56"
    name: "Client56"
  - id: "client_57"
    name: "Client57"
  - id: "client_58"
    name: "Client58"
  - id: "client_59"
    name: "Client59"

rounds:
  - number: 1
    actions:
      client_0:
        - type: "Onboard"
          amount: 0.00002000
      client_1:
        - type: "Onboard"
          amount: 0.00002000
      client_2:
        - type: "Onboard"
          amount: 0.00002000
      client_3:
        - type: "Onboard"
          amount: 0.00002000
      client_4:
        - type: "Onboard"
          amount: 0.00002000
      client_5:
        - type: "Onboard"
          amount: 0.00002000
      client_6:
        - type: "Onboard"
          amount: 0.00002000
      client_7:
        - type: "Onboard"
          amount: 0.00002000
      client_8:
        - type: "Onboard"
          amount: 0.00002000
      client_9:
        - type: "Onboard"
          amount: 0.00002000
      client_10:
        - type: "Onboard"
          amount: 0.00002000
      client_11:
        - type: "Onboard"
          amount: 0.00002000
      client_12:
        - type: "Onboard"
          amount: 0.00002000
      client_13:
        - type: "Onboard"
          amount: 0.00002000
      client_14:
        - type: "Onboard"
          amount: 0.00002000
      client_15:
        - type: "Onboard"
          amount: 0.00002000
      client_16:
        - type: "Onboard"
          amount: 0.00002000
      client_17:
        - type: "Onboard"
          amount: 0.00002000
      client_18:
        - type: "Onboard"
          amount: 0.00002000
      client_19:
        - type: "Onboard"
          amount: 0.00002000
      client_20:
        - type: "Onboard"
          amount: 0.00002000
      client_21:
        - type: "Onboard"
          amount: 0.00002000
      client_22:
        - type: "Onboard"
          amount: 0.00002000
      client_23:
        - type: "Onboard"
          amount: 0.00002000
      client_24:
        - type: "Onboard"
          amount: 0.00002000
      client_25:
        - type: "Onboard"
          amount: 0.00002000
      client_26:
        - type: "Onboard"
          amount: 0.00002000
      client_27:
        - type: "Onboard"
          amount: 0.00002000
      client_28:
        - type: "Onboard"
          amount: 0.00002000
      client_29:
        - type: "Onboard"
          amount: 0.00002000
      client_30:
        - type: "Onboard"
          amount: 0.00002000
      client_31:
        - type: "Onboard"
          amount: 0.00002000
      client_32:
        - type: "Onboard"
          amount: 0.00002000
      client_33:
        - type: "Onboard"
          amount: 0.00002000
      client_34:
        - type: "Onboard"
          amount: 0.00002000
      client_35:
        - type: "Onboard"
          amount: 0.00002000
      client_36:
        - type: "Onboard"
          amount: 0.00002000
      client_37:
        - type: "Onboard"
          amount: 0.00002000
      client_38:
        - type: "Onboard"
          amount: 0.00002000
      client_39:
        - type: "Onboard"
          amount: 0.00002000
      client_40:
        - type: "Onboard"
          amount: 0.00002000
      client_41:
        - type: "Onboard"
          amount: 0.00002000
      client_42:
        - type: "Onboard"
          amount: 0.00002000
      client_43:
        - type: "Onboard"
          amount: 0.00002000
      client_44:
        - type: "Onboard"
          amount: 0.00002000
      client_45:
        - type: "Onboard"
          amount: 0.00002000
      client_46:
        - type: "Onboard"
          amount: 0.00002000
      client_47:
        - type: "Onboard"
          amount: 0.00002000
      client_48:
        - type: "Onboard"
          amount: 0.00002000
      client_49:
        - type: "Onboard"
          amount: 0.00002000
      client_50:
        - type: "Onboard"
          amount: 0.00002000
      client_51:
        - type: "Onboard"
          amount: 0.00002000
      client_52:
        - type: "Onboard"
          amount: 0.00002000
      client_53:
        - type: "Onboard"
          amount: 0.00002000
      client_54:
        - type: "Onboard"
          amount: 0.00002000
      client_55:
        - type: "Onboard"
          amount: 0.00002000
      client_56:
        - type: "Onboard"
          amount: 0.00002000
      client_57:
        - type: "Onboard"
          amount: 0.00002000
      client_58:
        - type: "Onboard"
          amount: 0.00002000
      client_59:
        - type: "Onboard"
          amount: 0.00002000

  - number: 2
    actions:
      client_0:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_1:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_2:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_3:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_4:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_5:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_6:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_7:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_8:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_9:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_10:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_11:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_12:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_13:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_14:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_15:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_16:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_17:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_18:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_19:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_20:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_21:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_22:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_23:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_24:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_25:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_26:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_27:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_28:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_29:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_30:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_31:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_32:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_33:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_34:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_35:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_36:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_37:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_38:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_39:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_40:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_41:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_42:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_43:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_44:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_45:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_46:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_47:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_48:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_49:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_50:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_51:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_52:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_53:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_54:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_55:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_56:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_57:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"
      client_58:
        - type: "SendAsync"
          amount: 0.00002000
          to: "client_59"

  - number: 3
    actions:
      client_59:
        - type: "Claim"

  - number: 4
    actions:
      client_59:
        - type: "Stats"