version: "3.9"

networks:
  dokploy-network:
    external: true

services:
  ########################
  # Prometheus
  ########################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - dokploy-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  ########################
  # Grafana
  ########################
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - dokploy-network
    ports:
      - "3333:3000"
    restart: unless-stopped
    depends_on:
      - prometheus