name: Verify SDK Autogen REST Client

on:
  push:
    branches: 
      - master
    paths:
      - "api-spec/**"
  pull_request:
    branches:
      - master
    paths:
      - "api-spec/**"

jobs:
  verify-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.23.1'

    - name: Run go work sync
      run: go work sync

    - name: Install Swagger
      run: go install github.com/go-swagger/go-swagger/cmd/swagger@latest

    - name: Generate Client
      working-directory: pkg/client-sdk
      run: make genrest

    - name: Check for uncommitted changes
      run: |
        git add .
        git diff --staged --exit-code

    - name: Fail if changes detected
      if: failure()
      run: |
        echo "❌ Generated client is out of date!"
        echo "Please run 'make genrest' and commit the changes."
        exit 1